on:
  push:
    branches: [ master ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '19'
      - run: mvn test
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 19 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: build
        run: |
          mvn -B package
